name: skru_mate
description: "A new Flutter project."
publish_to: 'none'

version: 2.0.1+5

environment:
  sdk: ^3.12.1

dependencies:
  flutter:
    sdk: flutter

  # UI & Design
  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3
  gap: ^3.0.1
  google_fonts: ^8.0.0
  flutter_svg: ^2.2.3
  flutter_animate: ^4.5.2
  flutter_slidable: ^4.0.0
  confetti: ^0.8.0
  fluttertoast: ^8.2.12
  toastification: ^2.3.0

  # State Management & Architecture
  flutter_bloc: ^9.1.1
  get_it: ^8.0.3
  dartz: ^0.10.1

  # Database & Utilities
  sqflite: ^2.4.2
  path: any
  intl: ^0.20.2
  logger: ^2.7.0
  shared_preferences: ^2.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

  # Tools & Generators
  flutter_native_splash: ^2.4.6
  flutter_launcher_icons: ^0.14.4
  rename: ^3.1.0

# ==========================================
# Configuration: Launcher Icons
# ==========================================
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.png"
  min_sdk_android: 21

# ==========================================
# Configuration: Native Splash Screen
# ==========================================
flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/app_icon.png
  color_dark: "#131013"
  image_dark: assets/images/app_icon_transparent.png
  android_12:
    image: assets/images/splash_android_12.png
    icon_background_color: "#FFFFFF"
    image_dark: assets/images/splash_android_12_dark.png
    icon_background_color_dark: "#131013"

# ==========================================
# Flutter Config
# ==========================================
flutter:
  uses-material-design: true

  assets:
    - assets/svgs/
    - assets/images/